POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "tester3@gmail.com",
  "password": "0000"
}

### Sign up
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "tester1",
  "email": "tester1@gmail.com",
  "password": "0000"
}

### Delete
DELETE http://localhost:3000/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0ZXIzQGdtYWlsLmNvbSIsImlhdCI6MTc4MzE2NDA5NCwiZXhwIjoxNzgzMTY3Njk0fQ.5W0Xv6t3xHoPJIntzHDKmsN4NzJcuzpO_w6Yl6XyFjM
